# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e66fc223aaf7a9e5195ab4d59f5ae5312bdd72a2c16417de083abbb2ebb99964abf171de5733f1bb4e63da0f0a236fde072a828b167b58d48c6d5f96a36c18c2

test:
  secret_key_base: 7a1627322f422e9adf06fba822fa4c3cea03693d024be31974988cde8a6928000ecf70fae7c116d94a52828f9619dc4c58d626d562e9fbdce2544d4fbe637283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
